
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PTVIRG = 8;
  public static final int INTEIRO = 13;
  public static final int MENOR = 10;
  public static final int ACOLCH = 4;
  public static final int EOF = 0;
  public static final int MAIS_MAIS = 11;
  public static final int IF = 2;
  public static final int ID = 12;
  public static final int ELSE = 3;
  public static final int IGUAL = 9;
  public static final int error = 1;
  public static final int FPARENT = 7;
  public static final int APARENT = 6;
  public static final int FCOLCH = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "ACOLCH",
  "FCOLCH",
  "APARENT",
  "FPARENT",
  "PTVIRG",
  "IGUAL",
  "MENOR",
  "MAIS_MAIS",
  "ID",
  "INTEIRO"
  };
}

